-- require('markdown').setup({
--     -- Set the path to your Chrome executable
--     path_to_chrome =  "firefox",
--     -- Automatically start the preview when opening a markdown file
--     auto_start = true,
--     -- Other configuration options here
-- })
